FROM python:3.13-slim

WORKDIR /app

COPY requirements-source-api.txt .

RUN pip install --no-cache-dir -r requirements-source-api.txt

COPY source_api ./source_api

EXPOSE 8000

CMD ["uvicorn", "source_api.main:app", "--host", "0.0.0.0", "--port", "8000"]